import static java.lang.Math.random;
import javax.sound.sampled.*;
import java.io.*;
import java.util.Random;
import java.util.Scanner;
public class Main {
    public static void main(String[] args) throws UnsupportedAudioFileException, IOException, LineUnavailableException {

        /*Scanner sc= new Scanner(System.in);
        try{
            System.out.println("first num");
            int x=sc.nextInt();
            System.out.println("sec num");
            int y=sc.nextInt();
            int z=x/y;
        }
        catch (ArithmeticException e){
            System.out.println("bakayaro");
        }
        catch (Exception e){
            System.out.println("idk man somethings wrong i can feel it");
        }
        finally{
            System.out.println(" left side of my head hurts");
        }*/
//file= an abstract representation of file and directory pathnames
       /* File file=new File("/C:/Users/canfu/Desktop/testingint/");
        if(file.exists()){
            System.out.println("yea");
            System.out.println(file.getPath());
            System.out.println(file.getAbsoluteFile());
            System.out.println(file.isFile());
            System.out.println(file.delete());
        }
        else {
            System.out.println("that file doesnt exist");
        }*/
    //filewriter
      /* try {
           FileWriter writer = new FileWriter("dontknow.txt");
           writer.write("  idk man \n idk too");
           writer.append("\n i dont know");

           writer.close();
       } catch (IOException e) {
           //autogenerated
           throw new RuntimeException(e);
       }*/
        //filereader=read the contents of a file as a stream of characters. one by one
        // read() returns an int  value which containts the byte value
        // when read() returns -1, there is no more data to be read.
        /*try{
            FileReader reader=new FileReader("stilldontknow.txt");

            int data=reader.read();
            while(data!=-1){
                System.out.print((char)data);
                data=reader.read();
                 }
            reader.close();
        } catch (FileNotFoundException e) {
            //autogenerated
            throw new RuntimeException(e);
        } catch (IOException e) {
            //autogenerated by read().
            throw new RuntimeException(e);
        }*/
        Scanner sc=new Scanner(System.in);
        File file=new File("dreams.wav");
        AudioInputStream audioStream=AudioSystem.getAudioInputStream(file);
        Clip clip=AudioSystem.getClip();
        clip.open(audioStream);

        String response="";

        while(!response.equals("Q")){
            System.out.println("P=play, S=stop, R=reset, Q=quit, F=fast forward 10 seconds(fast forward doesnt work");
            System.out.println("Enter your choice");

            response=sc.next();
            response=response.toUpperCase();

            switch (response){
                case("P"):clip.start();
                break;
                case("Q"):clip.close();
                break;
                case("R"):clip.setMicrosecondPosition(0);
                break;
               // case("F"):clip.setMicrosecondPosition(++10);
                //break;
                case("S"):clip.stop();
                break;
                default:
                    System.out.println("That is not a valid choice.");

            }
        }
    }
}
